version: 2
jobs:
  build:
    working_directory: /go/src/github.com/hatena/mackerel-agent
    docker:
    - image: circleci/golang:1.11
    steps:
    - checkout
    - restore_cache:
        keys:
          - v1-pkg-cache
    - run:
        name: Get CI dependency
        command: go get github.com/jstemmer/go-junit-report
    - run: make lint
    - run: make cover
    - run: test `gofmt -l . | wc -l` = 0
    - save_cache:
        key: v1-pkg-cache
        paths:
          - "/go/pkg"
